[build]
  base = "yuscheduler-frontend"
  publish = "yuscheduler-frontend/build"
  command = "cd yuscheduler-frontend && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 